-- ============================================================================
-- SECTION 1: model_deployments table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.model_deployments (
    -- Unique internal identifier for the model version record.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Logical model name (for example, FraudDetectionModel).
    model_name TEXT NOT NULL,

    -- Human-readable model version (for example, v1, v1.2.0).
    version TEXT NOT NULL,

    -- Unique MLflow run identifier for traceability.
    mlflow_run_id TEXT NOT NULL,

    -- Timestamp when this model version was registered.
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Flag that indicates if this version is currently active in production.
    is_active BOOLEAN NOT NULL DEFAULT FALSE,

    -- F1 score measured from confirmed production outcomes.
    f1_score DOUBLE PRECISION,

    -- Precision measured from confirmed production outcomes.
    precision DOUBLE PRECISION,

    -- Recall measured from confirmed production outcomes.
    recall DOUBLE PRECISION,

    -- AUC-ROC score associated with this model version.
    auc_roc DOUBLE PRECISION,

    -- Start timestamp of the training data window used for this model.
    training_data_from TIMESTAMPTZ NOT NULL,

    -- End timestamp of the training data window used for this model.
    training_data_to TIMESTAMPTZ NOT NULL,

    CONSTRAINT model_deployments_mlflow_run_id_uk UNIQUE (mlflow_run_id),
    CONSTRAINT model_deployments_training_range_ck
        CHECK (training_data_from <= training_data_to),
    CONSTRAINT model_deployments_f1_score_ck
        CHECK (f1_score IS NULL OR (f1_score >= 0 AND f1_score <= 1)),
    CONSTRAINT model_deployments_precision_ck
        CHECK (precision IS NULL OR (precision >= 0 AND precision <= 1)),
    CONSTRAINT model_deployments_recall_ck
        CHECK (recall IS NULL OR (recall >= 0 AND recall <= 1)),
    CONSTRAINT model_deployments_auc_roc_ck
        CHECK (auc_roc IS NULL OR (auc_roc >= 0 AND auc_roc <= 1))
);

CREATE INDEX IF NOT EXISTS idx_model_deployments_active
    ON public.model_deployments (created_at DESC)
    WHERE is_active IS TRUE;

-- ============================================================================
-- SECTION 2: predictions_history table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.predictions_history (
    -- Unique internal identifier of the prediction event.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Transaction identifier to correlate with transactional sources.
    transaction_id UUID NOT NULL,

    -- Model version identifier used to generate this prediction.
    model_version_id BIGINT NOT NULL,

    -- Raw fraud probability score returned by the model.
    prediction_score DOUBLE PRECISION NOT NULL,

    -- Predicted fraud label (TRUE means predicted fraud).
    prediction_label BOOLEAN NOT NULL,

    -- Ground-truth label, populated later when available.
    actual_label BOOLEAN,

    -- Inference timestamp for this prediction event.
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- End-to-end inference latency in milliseconds.
    latency_ms DOUBLE PRECISION NOT NULL,

    CONSTRAINT predictions_history_model_version_fk
        FOREIGN KEY (model_version_id)
        REFERENCES public.model_deployments (id),
    CONSTRAINT predictions_history_prediction_score_ck
        CHECK (prediction_score >= 0 AND prediction_score <= 1),
    CONSTRAINT predictions_history_latency_ms_ck
        CHECK (latency_ms >= 0)
);

CREATE INDEX IF NOT EXISTS idx_predictions_history_model_version_id
    ON public.predictions_history (model_version_id);

CREATE INDEX IF NOT EXISTS idx_predictions_history_timestamp
    ON public.predictions_history ("timestamp");

CREATE INDEX IF NOT EXISTS idx_predictions_history_transaction_id
    ON public.predictions_history (transaction_id);

-- ============================================================================
-- SECTION 3: drift_reports table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.drift_reports (
    -- Unique internal identifier for each drift report.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Timestamp when the drift analysis report was generated.
    report_date TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Model version evaluated by this drift report.
    model_version_id BIGINT NOT NULL,

    -- Global drift score produced by the drift analysis.
    drift_score DOUBLE PRECISION NOT NULL,

    -- Per-feature drift details stored as flexible JSONB.
    feature_drifts JSONB NOT NULL,

    -- Indicates whether the report triggered an operational alert.
    alert_triggered BOOLEAN NOT NULL DEFAULT FALSE,

    -- Optional remediation action taken after this report.
    remediation_action TEXT,

    CONSTRAINT drift_reports_model_version_fk
        FOREIGN KEY (model_version_id)
        REFERENCES public.model_deployments (id),
    CONSTRAINT drift_reports_drift_score_ck
        CHECK (drift_score >= 0 AND drift_score <= 1)
);

CREATE INDEX IF NOT EXISTS idx_drift_reports_report_date
    ON public.drift_reports (report_date);

CREATE INDEX IF NOT EXISTS idx_drift_reports_model_version_id
    ON public.drift_reports (model_version_id);

CREATE INDEX IF NOT EXISTS idx_drift_reports_alerts_true
    ON public.drift_reports (report_date DESC)
    WHERE alert_triggered IS TRUE;

-- ============================================================================
-- SECTION 4: alert_log table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.alert_log (
    -- Unique internal identifier for the alert event.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Alert category/type (for example, HIGH_FRAUD_RATE or DRIFT_DETECTED).
    alert_type TEXT NOT NULL,

    -- Operational severity level of the alert.
    severity TEXT NOT NULL,

    -- Human-readable alert message for operators.
    message TEXT NOT NULL,

    -- Timestamp when the alert was triggered.
    triggered_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Timestamp when the alert was acknowledged.
    acknowledged_at TIMESTAMPTZ,

    -- User or operator that acknowledged the alert.
    acknowledged_by TEXT,

    CONSTRAINT alert_log_severity_ck
        CHECK (severity IN ('INFO', 'WARNING', 'HIGH', 'CRITICAL'))
);

CREATE INDEX IF NOT EXISTS idx_alert_log_triggered_at
    ON public.alert_log (triggered_at DESC);

CREATE INDEX IF NOT EXISTS idx_alert_log_open_unack
    ON public.alert_log (triggered_at DESC)
    WHERE acknowledged_at IS NULL;

CREATE INDEX IF NOT EXISTS idx_alert_log_severity
    ON public.alert_log (severity);

-- ============================================================================
-- SECTION 5: audit_log table
-- ============================================================================

CREATE TABLE IF NOT EXISTS public.audit_log (
    -- Unique internal identifier for the audit record.
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- Name of the table affected by the audited operation.
    "table" TEXT NOT NULL,

    -- Operation performed on the affected record.
    "operation" TEXT NOT NULL,

    -- Database user that performed the operation.
    "user" TEXT NOT NULL DEFAULT CURRENT_USER,

    -- Timestamp when the audit event was captured.
    "timestamp" TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    -- Row state before the operation (NULL for INSERT).
    old_values JSONB,

    -- Row state after the operation (NULL for DELETE).
    new_values JSONB,

    CONSTRAINT audit_log_operation_ck
        CHECK ("operation" IN ('INSERT', 'UPDATE', 'DELETE', 'ACTIVATE'))
);

CREATE INDEX IF NOT EXISTS idx_audit_log_table
    ON public.audit_log ("table");

CREATE INDEX IF NOT EXISTS idx_audit_log_timestamp
    ON public.audit_log ("timestamp" DESC);

CREATE INDEX IF NOT EXISTS idx_audit_log_user
    ON public.audit_log ("user");

-- ============================================================================
-- SECTION 6: Stored functions
-- ============================================================================

CREATE OR REPLACE FUNCTION public.activate_model_version(p_model_version_id INTEGER)
RETURNS VOID
LANGUAGE plpgsql
AS $$
DECLARE
    v_target RECORD;
    v_old_active RECORD;
    v_old_values JSONB;
    v_new_values JSONB;
BEGIN
    RAISE NOTICE 'activate_model_version start: model_version_id=%', p_model_version_id;

    SELECT mv.id, mv.model_name, mv.version, mv.is_active
    INTO v_target
    FROM public.model_deployments AS mv
    WHERE mv.id = p_model_version_id
    FOR UPDATE;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'activate_model_version failed: model_version_id % does not exist in model_deployments',
            p_model_version_id;
    END IF;

    SELECT mv.id, mv.model_name, mv.version, mv.is_active
    INTO v_old_active
    FROM public.model_deployments AS mv
    WHERE mv.is_active IS TRUE
      AND mv.id <> p_model_version_id
    ORDER BY mv.created_at DESC, mv.id DESC
    LIMIT 1
    FOR UPDATE;

    IF FOUND THEN
        v_old_values := jsonb_build_object(
            'id', v_old_active.id,
            'model_name', v_old_active.model_name,
            'version', v_old_active.version,
            'is_active', TRUE
        );

        RAISE NOTICE
            'Previous active model found: id=%, model_name=%, version=%',
            v_old_active.id, v_old_active.model_name, v_old_active.version;
    ELSE
        v_old_values := NULL;
        RAISE NOTICE 'No previously active model found (first activation case).';
    END IF;

    RAISE NOTICE 'Deactivating all active versions except id=%', p_model_version_id;
    UPDATE public.model_deployments
    SET is_active = FALSE
    WHERE is_active IS TRUE
      AND id <> p_model_version_id;

    RAISE NOTICE 'Activating model_version_id=%', p_model_version_id;
    UPDATE public.model_deployments
    SET is_active = TRUE
    WHERE id = p_model_version_id;

    v_new_values := jsonb_build_object(
        'id', v_target.id,
        'model_name', v_target.model_name,
        'version', v_target.version,
        'is_active', TRUE
    );

    INSERT INTO public.audit_log (
        "table",
        "operation",
        "user",
        "timestamp",
        old_values,
        new_values
    )
    VALUES (
        'model_deployments',
        'ACTIVATE',
        CURRENT_USER,
        NOW(),
        v_old_values,
        v_new_values
    );

    RAISE NOTICE 'activate_model_version complete: model_version_id=%', p_model_version_id;
END;
$$;


CREATE OR REPLACE FUNCTION public.calculate_model_metrics(
    p_model_version_id INTEGER,
    p_date_from TIMESTAMPTZ,
    p_date_to TIMESTAMPTZ
)
RETURNS TABLE (
    "precision" DOUBLE PRECISION,
    "recall" DOUBLE PRECISION,
    f1_score DOUBLE PRECISION
)
LANGUAGE plpgsql
AS $$
DECLARE
    v_min_confirmed_records INTEGER := 100;
    v_confirmed_count INTEGER;
    v_tp INTEGER;
    v_fp INTEGER;
    v_fn INTEGER;
    v_precision DOUBLE PRECISION;
    v_recall DOUBLE PRECISION;
    v_f1_score DOUBLE PRECISION;
BEGIN
    IF p_date_from >= p_date_to THEN
        RAISE EXCEPTION
            'calculate_model_metrics failed: p_date_from (%) must be earlier than p_date_to (%)',
            p_date_from,
            p_date_to;
    END IF;

    PERFORM 1
    FROM public.model_deployments AS mv
    WHERE mv.id = p_model_version_id;

    IF NOT FOUND THEN
        RAISE EXCEPTION
            'calculate_model_metrics failed: model_version_id % does not exist in model_deployments',
            p_model_version_id;
    END IF;

    SELECT
        COUNT(*)::INTEGER,
        COALESCE(SUM(CASE
            WHEN ph.prediction_label IS TRUE AND ph.actual_label IS TRUE THEN 1
            ELSE 0
        END), 0)::INTEGER,
        COALESCE(SUM(CASE
            WHEN ph.prediction_label IS TRUE AND ph.actual_label IS FALSE THEN 1
            ELSE 0
        END), 0)::INTEGER,
        COALESCE(SUM(CASE
            WHEN ph.prediction_label IS FALSE AND ph.actual_label IS TRUE THEN 1
            ELSE 0
        END), 0)::INTEGER
    INTO
        v_confirmed_count,
        v_tp,
        v_fp,
        v_fn
    FROM public.predictions_history AS ph
    WHERE ph.model_version_id = p_model_version_id
      AND ph."timestamp" >= p_date_from
      AND ph."timestamp" < p_date_to
      AND ph.actual_label IS NOT NULL;

    IF v_confirmed_count < v_min_confirmed_records THEN
        RAISE NOTICE
            'calculate_model_metrics skipped: confirmed_records=% is below minimum=% for model_version_id=%',
            v_confirmed_count,
            v_min_confirmed_records,
            p_model_version_id;

        RETURN QUERY
        SELECT
            NULL::DOUBLE PRECISION AS "precision",
            NULL::DOUBLE PRECISION AS "recall",
            NULL::DOUBLE PRECISION AS f1_score;
        RETURN;
    END IF;

    IF (v_tp + v_fp) > 0 THEN
        v_precision := v_tp::DOUBLE PRECISION / (v_tp + v_fp);
    ELSE
        v_precision := 0.0;
    END IF;

    IF (v_tp + v_fn) > 0 THEN
        v_recall := v_tp::DOUBLE PRECISION / (v_tp + v_fn);
    ELSE
        v_recall := 0.0;
    END IF;

    IF (v_precision + v_recall) > 0 THEN
        v_f1_score := 2.0 * (v_precision * v_recall) / (v_precision + v_recall);
    ELSE
        v_f1_score := 0.0;
    END IF;

    RAISE NOTICE
        'calculate_model_metrics: model_version_id=%, confirmed=%, tp=%, fp=%, fn=%, precision=%, recall=%, f1_score=%',
        p_model_version_id,
        v_confirmed_count,
        v_tp,
        v_fp,
        v_fn,
        v_precision,
        v_recall,
        v_f1_score;

    UPDATE public.model_deployments
    SET
        precision = v_precision,
        recall = v_recall,
        f1_score = v_f1_score
    WHERE id = p_model_version_id;

    RETURN QUERY
    SELECT
        v_precision AS "precision",
        v_recall AS "recall",
        v_f1_score AS f1_score;
END;
$$;


CREATE OR REPLACE FUNCTION public.check_fraud_rate()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_fraud_threshold DOUBLE PRECISION := 0.05;
    v_window_minutes INTEGER := 15;
    v_window_interval INTERVAL := INTERVAL '15 minutes';

    v_reference_ts TIMESTAMPTZ := COALESCE(NEW."timestamp", NOW());
    v_total_count BIGINT := 0;
    v_fraud_count BIGINT := 0;
    v_fraud_rate DOUBLE PRECISION := 0.0;
    v_has_recent_open_alert BOOLEAN := FALSE;

    v_alert_message TEXT;
    v_notify_payload TEXT;
BEGIN
    SELECT
        COUNT(*)::BIGINT,
        COALESCE(SUM(CASE WHEN ph.prediction_label IS TRUE THEN 1 ELSE 0 END), 0)::BIGINT
    INTO
        v_total_count,
        v_fraud_count
    FROM public.predictions_history AS ph
    WHERE ph."timestamp" >= (v_reference_ts - v_window_interval)
      AND ph."timestamp" <= v_reference_ts;

    IF v_total_count > 0 THEN
        v_fraud_rate := v_fraud_count::DOUBLE PRECISION / v_total_count::DOUBLE PRECISION;
    ELSE
        v_fraud_rate := 0.0;
    END IF;

    RAISE NOTICE
        'check_fraud_rate: fraud_rate=%, fraud_count=%, total_count=%, window_minutes=%',
        v_fraud_rate,
        v_fraud_count,
        v_total_count,
        v_window_minutes;

    SELECT EXISTS (
        SELECT 1
        FROM public.alert_log AS al
        WHERE al.alert_type = 'HIGH_FRAUD_RATE'
          AND al.acknowledged_at IS NULL
          AND al.triggered_at >= (v_reference_ts - v_window_interval)
    )
    INTO v_has_recent_open_alert;

    IF v_fraud_rate > v_fraud_threshold AND NOT v_has_recent_open_alert THEN
        v_alert_message := format(
            'High fraud rate detected: %s%% over the last %s minutes (%s/%s predictions).',
            to_char(v_fraud_rate * 100.0, 'FM999990.00'),
            v_window_minutes,
            v_fraud_count,
            v_total_count
        );

        INSERT INTO public.alert_log (
            alert_type,
            severity,
            message,
            triggered_at
        )
        VALUES (
            'HIGH_FRAUD_RATE',
            'HIGH',
            v_alert_message,
            v_reference_ts
        );

        v_notify_payload := jsonb_build_object(
            'fraud_rate', round(v_fraud_rate::NUMERIC, 6),
            'window_minutes', v_window_minutes,
            'triggered_at', v_reference_ts
        )::TEXT;

        PERFORM pg_notify('fraud_alerts', v_notify_payload);

        RAISE NOTICE 'check_fraud_rate: HIGH_FRAUD_RATE alert inserted and pg_notify emitted.';
    END IF;

    RETURN NEW;
END;
$$;


CREATE OR REPLACE FUNCTION public.audit_trigger()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    v_old_values JSONB;
    v_new_values JSONB;
BEGIN
    RAISE NOTICE 'audit_trigger: table=%, operation=%', TG_TABLE_NAME, TG_OP;

    IF TG_OP = 'INSERT' THEN
        v_old_values := NULL;
        v_new_values := row_to_json(NEW)::JSONB;

        INSERT INTO public.audit_log (
            "table",
            "operation",
            "user",
            "timestamp",
            old_values,
            new_values
        )
        VALUES (
            TG_TABLE_NAME,
            TG_OP,
            CURRENT_USER,
            NOW(),
            v_old_values,
            v_new_values
        );

        RETURN NEW;
    ELSIF TG_OP = 'UPDATE' THEN
        v_old_values := row_to_json(OLD)::JSONB;
        v_new_values := row_to_json(NEW)::JSONB;

        INSERT INTO public.audit_log (
            "table",
            "operation",
            "user",
            "timestamp",
            old_values,
            new_values
        )
        VALUES (
            TG_TABLE_NAME,
            TG_OP,
            CURRENT_USER,
            NOW(),
            v_old_values,
            v_new_values
        );

        RETURN NEW;
    ELSIF TG_OP = 'DELETE' THEN
        v_old_values := row_to_json(OLD)::JSONB;
        v_new_values := NULL;

        INSERT INTO public.audit_log (
            "table",
            "operation",
            "user",
            "timestamp",
            old_values,
            new_values
        )
        VALUES (
            TG_TABLE_NAME,
            TG_OP,
            CURRENT_USER,
            NOW(),
            v_old_values,
            v_new_values
        );

        RETURN OLD;
    ELSE
        RAISE EXCEPTION
            'audit_trigger failed: unsupported operation "%" on table "%"',
            TG_OP,
            TG_TABLE_NAME;
    END IF;
END;
$$;

-- ============================================================================
-- SECTION 7: Triggers
-- ============================================================================

DROP TRIGGER IF EXISTS alert_on_high_fraud_rate ON public.predictions_history;

CREATE TRIGGER alert_on_high_fraud_rate
AFTER INSERT ON public.predictions_history
FOR EACH ROW
EXECUTE FUNCTION public.check_fraud_rate();


DROP TRIGGER IF EXISTS audit_model_deployments ON public.model_deployments;

CREATE TRIGGER audit_model_deployments
AFTER INSERT OR UPDATE OR DELETE ON public.model_deployments
FOR EACH ROW
EXECUTE FUNCTION public.audit_trigger();


DROP TRIGGER IF EXISTS audit_predictions_history ON public.predictions_history;

CREATE TRIGGER audit_predictions_history
AFTER INSERT OR UPDATE OR DELETE ON public.predictions_history
FOR EACH ROW
EXECUTE FUNCTION public.audit_trigger();

-- ============================================================================
-- VERIFICATION QUERIES (manual execution)
-- ============================================================================

-- 1) Confirm all core PostgreSQL tables exist
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
--   AND table_name IN (
--       'model_deployments',
--       'predictions_history',
--       'drift_reports',
--       'alert_log',
--       'audit_log'
--   )
-- ORDER BY table_name;

-- 2) Confirm indexes for operational queries
-- SELECT schemaname, tablename, indexname, indexdef
-- FROM pg_indexes
-- WHERE schemaname = 'public'
--   AND tablename IN (
--       'model_deployments',
--       'predictions_history',
--       'drift_reports',
--       'alert_log',
--       'audit_log'
--   )
-- ORDER BY tablename, indexname;

-- 3) Confirm functions exist
-- SELECT n.nspname AS schema_name, p.proname AS function_name
-- FROM pg_proc p
-- JOIN pg_namespace n ON n.oid = p.pronamespace
-- WHERE n.nspname = 'public'
--   AND p.proname IN (
--       'activate_model_version',
--       'calculate_model_metrics',
--       'check_fraud_rate',
--       'audit_trigger'
--   )
-- ORDER BY function_name;

-- 4) Confirm triggers are active
-- SELECT trigger_name, event_object_table, action_timing, event_manipulation
-- FROM information_schema.triggers
-- WHERE trigger_schema = 'public'
--   AND trigger_name IN (
--       'alert_on_high_fraud_rate',
--       'audit_model_deployments',
--       'audit_predictions_history'
--   )
-- ORDER BY trigger_name;
